# Generated by Django 4.2.15 on 2024-09-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_Time',
        ),
    ]
